require("bernard.plugins-setup")

require("bernard.core.options")
require("bernard.core.keymaps")
require("bernard.core.colorscheme")
require("bernard.plugins.comment")
require("bernard.plugins.nvim-tree")
require("bernard.plugins.lualine")
require("bernard.plugins.telescope")
require("bernard.plugins.cmp")
require("bernard.plugins.lsp.mason")
require("bernard.plugins.lsp.lspsaga")
require("bernard.plugins.lsp.lspconfig")
require("bernard.plugins.lsp.null-ls")
require("bernard.plugins.autopairs")
require("bernard.plugins.treesitter")
require("bernard.plugins.gitsigns")
require("bernard.plugins.transparency")
